name: Java CI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
#     - name: Build and Release
#       uses: qcastel/github-actions-maven-release@master
#       with:
#         release-branch-name: "master"
        
#         git-release-bot-name: "release-bot"
#         git-release-bot-email: "release-bot@example.com"
        
#         access-token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: List Target Directory
      run: ls -l /home/runner/work/killbill-email-notifications-plugin/killbill-email-notifications-plugin/target/
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
        asset_path: /home/runner/work/killbill-email-notifications-plugin/killbill-email-notifications-plugin/target/killbill-email-notifications-plugin-0.5.2-SNAPSHOT.jar
        asset_name: killbill-email-notifications-plugin-${{ github.ref }}.jar
        asset_content_type: application/jar
